/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.agave.client.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApplicationParameter 
        extends ApplicationArgument {
    private static final long serialVersionUID = 5191953399745010589L;
    private AbstractApplicationParameterValue value;
    /** GETTER
     * The inputs files for this parameter. 
     */
    @JsonGetter("value")
    public AbstractApplicationParameterValue getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * The inputs files for this parameter. 
     */
    @JsonSetter("value")
    public void setValue (AbstractApplicationParameterValue value) { 
        this.value = value;
    }
 
}
 