/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.agave.client.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApplicationDisableAction 
        extends ApplicationAction {
    private static final long serialVersionUID = 5005466122747888403L;
    private ApplicationActionTypeEnum action = ApplicationActionTypeEnum.fromString("DISABLE");
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("action")
    public ApplicationActionTypeEnum getAction ( ) { 
        return this.action;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("action")
    private void setAction (ApplicationActionTypeEnum value) { 
        this.action = value;
    }
 
}
 