/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.agave.client.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SystemAction 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5646142366707973004L;
    private SystemActionTypeEnum action;
    /** GETTER
     * Action to perform on the system.
     */
    @JsonGetter("action")
    public SystemActionTypeEnum getAction ( ) { 
        return this.action;
    }
    
    /** SETTER
     * Action to perform on the system.
     */
    @JsonSetter("action")
    public void setAction (SystemActionTypeEnum value) { 
        this.action = value;
    }
 
}
 