/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.iplantc.agave.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AgaveNullResponse 
        extends AgaveResponse {
    private static final long serialVersionUID = 5630820069056148252L;
    private String result;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("result")
    public String getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("result")
    private void setResult (String value) { 
        this.result = value;
    }
 
}
 