/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.iplantc.agave.models;

import java.util.*;

public class FilePermissionStanzaBuilder 
        extends PermissionStanzaBuilder {
    //the instance to build
    private FilePermissionStanza filePermissionStanza;

    /**
     * Default constructor to initialize the instance
     */
    public FilePermissionStanzaBuilder() {
        filePermissionStanza = new FilePermissionStanza();
    }

    /**
     * Is the resource executable
     */
    public FilePermissionStanzaBuilder execute(boolean execute) {
        filePermissionStanza.setExecute(execute);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FilePermissionStanza build() {
        return filePermissionStanza;
    }
}