/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.iplantc.agave.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class JobParameters 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5687515268329325519L;
    private String parameter1;
    /** GETTER
     * One or more parameters identified in the description of the app you're running. 
     */
    @JsonGetter("parameter1")
    public String getParameter1 ( ) { 
        return this.parameter1;
    }
    
    /** SETTER
     * One or more parameters identified in the description of the app you're running. 
     */
    @JsonSetter("parameter1")
    public void setParameter1 (String value) { 
        this.parameter1 = value;
    }
 
}
 