/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.iplantc.agave.models;

import java.util.*;

public class JobResubmitActionBuilder 
        extends JobActionBuilder {
    //the instance to build
    private JobResubmitAction jobResubmitAction;

    /**
     * Default constructor to initialize the instance
     */
    public JobResubmitActionBuilder() {
        jobResubmitAction = new JobResubmitAction();
    }

    public JobResubmitActionBuilder action(JobActionTypeEnum action) {
        jobResubmitAction.setAction(action);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public JobResubmitAction build() {
        return jobResubmitAction;
    }
}