/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.iplantc.agave.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StorageSystem 
        extends System {
    private static final long serialVersionUID = 5283241304607777357L;
    private SystemTypeEnum type = SystemTypeEnum.fromString("STORAGE");
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public SystemTypeEnum getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    private void setType (SystemTypeEnum value) { 
        this.type = value;
    }
 
}
 