/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.iplantc.agave.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SystemCloneAction 
        extends SystemAction {
    private static final long serialVersionUID = 4621636613519198923L;
    private String id;
    /** GETTER
     * Unique name for new system
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Unique name for new system
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
}
 