/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.iplantc.agave.models;

import java.util.*;

public class SystemPublishActionBuilder 
        extends SystemActionBuilder {
    //the instance to build
    private SystemPublishAction systemPublishAction;

    /**
     * Default constructor to initialize the instance
     */
    public SystemPublishActionBuilder() {
        systemPublishAction = new SystemPublishAction();
    }

    public SystemPublishActionBuilder action(String action) {
        systemPublishAction.setAction(action);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SystemPublishAction build() {
        return systemPublishAction;
    }
}