/*
 * AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */
package org.agave.client;
public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://agave.iplantc.org";

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static String oAuthAccessToken = "TODO: Replace";

}
